<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="3" failed="4" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[iam not present in my correct profile]]>
    </line>
    <line>
      <![CDATA[simple]]>
    </line>
  </reporter-output>
  <suite started-at="2025-06-03T14:01:17 IST" name="Suite" finished-at="2025-06-03T14:02:57 IST" duration-ms="99487">
    <groups>
    </groups>
    <test started-at="2025-06-03T14:01:17 IST" name="Test" finished-at="2025-06-03T14:02:57 IST" duration-ms="99487">
      <class name="TestCase.FunctionalTesting">
        <test-method is-config="true" signature="preCondition()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:18 IST" name="preCondition" finished-at="2025-06-03T14:01:24 IST" duration-ms="5965" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:24 IST" name="login" finished-at="2025-06-03T14:01:27 IST" duration-ms="3169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="dws()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:27 IST" name="dws" finished-at="2025-06-03T14:01:27 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestCase.FunctionalTesting.dws(FunctionalTesting.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dws -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:29 IST" name="logout" finished-at="2025-06-03T14:01:34 IST" duration-ms="4815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:34 IST" name="login" finished-at="2025-06-03T14:01:37 IST" duration-ms="3210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="pk()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:37 IST" name="pk" finished-at="2025-06-03T14:01:37 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestCase.FunctionalTesting.pk(FunctionalTesting.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pk -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:39 IST" name="logout" finished-at="2025-06-03T14:01:44 IST" duration-ms="4831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method signature="mi()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:44 IST" name="mi" finished-at="2025-06-03T14:01:44 IST" depends-on-methods="TestCase.FunctionalTesting.pk" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase.FunctionalTesting.mi() on instance TestCase.FunctionalTesting@792b749c depends on not successfully finished methods 
[TestCase.FunctionalTesting.pk() on instance TestCase.FunctionalTesting@792b749c]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase.FunctionalTesting.mi() on instance TestCase.FunctionalTesting@792b749c depends on not successfully finished methods 
[TestCase.FunctionalTesting.pk() on instance TestCase.FunctionalTesting@792b749c]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mi -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:44 IST" name="login" finished-at="2025-06-03T14:01:47 IST" duration-ms="3204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="rcb()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:47 IST" name="rcb" finished-at="2025-06-03T14:01:47 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rcb -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:47 IST" name="logout" finished-at="2025-06-03T14:01:52 IST" duration-ms="4829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="postCondition()[pri:0, instance:TestCase.FunctionalTesting@792b749c]" started-at="2025-06-03T14:01:52 IST" name="postCondition" finished-at="2025-06-03T14:01:52 IST" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- TestCase.FunctionalTesting -->
      <class name="TestCase.AdminModule">
        <test-method is-config="true" signature="preCondition()[pri:0, instance:TestCase.AdminModule@302c971f]" started-at="2025-06-03T14:01:52 IST" name="preCondition" finished-at="2025-06-03T14:01:58 IST" duration-ms="5488" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.AdminModule@302c971f]" started-at="2025-06-03T14:01:58 IST" name="login" finished-at="2025-06-03T14:02:01 IST" duration-ms="3147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="admin()[pri:0, instance:TestCase.AdminModule@302c971f]" started-at="2025-06-03T14:02:01 IST" name="admin" finished-at="2025-06-03T14:02:01 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- admin -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.AdminModule@302c971f]" started-at="2025-06-03T14:02:01 IST" name="logout" finished-at="2025-06-03T14:02:06 IST" duration-ms="4727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="postCondition()[pri:0, instance:TestCase.AdminModule@302c971f]" started-at="2025-06-03T14:02:06 IST" name="postCondition" finished-at="2025-06-03T14:02:06 IST" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- TestCase.AdminModule -->
      <class name="TestCase.HomePageModule">
        <test-method is-config="true" signature="preCondition()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:06 IST" name="preCondition" finished-at="2025-06-03T14:02:11 IST" duration-ms="5351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:11 IST" name="login" finished-at="2025-06-03T14:02:14 IST" duration-ms="3170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="profileCheck()[pri:1, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:14 IST" name="profileCheck" finished-at="2025-06-03T14:02:29 IST" duration-ms="15036" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestCase.HomePageModule.profileCheck(HomePageModule.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[iam not present in my correct profile]]>
            </line>
          </reporter-output>
        </test-method> <!-- profileCheck -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:31 IST" name="logout" finished-at="2025-06-03T14:02:37 IST" duration-ms="5130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:37 IST" name="login" finished-at="2025-06-03T14:02:41 IST" duration-ms="4059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="adminClick()[pri:2, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:41 IST" name="adminClick" finished-at="2025-06-03T14:02:41 IST" duration-ms="715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adminClick -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:41 IST" name="logout" finished-at="2025-06-03T14:02:46 IST" duration-ms="4758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:46 IST" name="login" finished-at="2025-06-03T14:02:49 IST" duration-ms="3122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="simple()[pri:3, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:49 IST" name="simple" finished-at="2025-06-03T14:02:50 IST" duration-ms="706" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [hava] but found [java]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [hava] but found [java]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestCase.HomePageModule.simple(HomePageModule.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[simple]]>
            </line>
          </reporter-output>
        </test-method> <!-- simple -->
        <test-method is-config="true" signature="logout()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:52 IST" name="logout" finished-at="2025-06-03T14:02:57 IST" duration-ms="4747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="postCondition()[pri:0, instance:TestCase.HomePageModule@1972e513]" started-at="2025-06-03T14:02:57 IST" name="postCondition" finished-at="2025-06-03T14:02:57 IST" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- TestCase.HomePageModule -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
